# Generated by Django 5.2.3 on 2025-07-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanakapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='service',
            field=models.CharField(blank=True, choices=[('Real Estate', 'Real Estate'), ('Ayurveda', 'Ayurveda'), ('Credit Cards', 'Credit Cards'), ('Banking', 'Banking'), ('Finance', 'Finance'), ('Insurance', 'Insurance'), ('E-commerce', 'E-commerce'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Travel', 'Travel'), ('Telecom', 'Telecom'), ('Investment', 'Investment'), ('Stock Market', 'Stock Market'), ('Mutual Funds', 'Mutual Funds'), ('Loans', 'Loans'), ('Home Loans', 'Home Loans'), ('Mortgage', 'Mortgage'), ('Wealth Management', 'Wealth Management')], max_length=50, null=True),
        ),
    ]
